[meta]
save_dir = "fsb_final/exp"
description = "This is a description of audiozen experiment."
seed = 3407
use_amp = false
use_deterministic_algorithms = false

[acoustics]
n_fft = 320
win_length = 320
sr = 16000
hop_length = 160


[loss_function]
name = "MultiResSpecLoss"
[loss_function.args]
n_ffts = [240, 480, 960, 1440]
gamma = 0.3
factor = 1
f_complex = 1


[optimizer]
lr = 0.001
beta1 = 0.9
beta2 = 0.999

# -------------------- Trainer -------------------- #
[trainer]
path = "trainer.Trainer"
[trainer.train]
max_epoch = 9999
clip_grad_norm_value = 10
save_max_score = true
save_checkpoint_interval = 5
[trainer.validate]
validation_interval = 5
max_num_checkpoints = 10

[train_dataset]
path = "dataset_train.Dataset"
[train_dataset.args]
sr = 16000
clean_dataset = "/data/ssp/public/data/dns/dns4_16k/track2/seg/all_train.txt"
point_noise_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/noise.txt"
simulated_rir_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/rir.txt"
real_rir_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/rir.txt"
iso_noise_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/noise.txt"
enrollment_dataset = "/data/ssp/public/data/dns/dns4_16k/track2/enrollment_wav/enrollment_wav.txt"
pt_noise_snr_range = [-5, 20]
iso_noise_snr_range = [-5, 20]
sir_range = [0, 25]
enroll_snr_range = [0, 25]
loudness_lvl = -26
loudness_floating_value = 10
prob_use_real_rir = 1.0 # use real rir for all data
prob_add_itf_spks = 0.0
max_num_itf_spks = 1
prob_add_point_noise = 0.0
max_num_pt_noises = 1
prob_add_iso_noise = 1.0
enroll_sample_length = 10
silence_length = 0.2
sample_length = 4
learning_target = "early"
len_early_rir = 0.1


[train_dataset.dataloader]
batch_size = 40
num_workers = 40
drop_last = true
pin_memory = false

# -------------------- Validation DNS 1 -------------------- #
[validation_dataset_dns_1]
path = "dataset_validation_dns_1.Dataset"
[validation_dataset_dns_1.args]
dataset_dir_list = [
    "/data/ssp/public/data/dns/dns1/test_set/synthetic/with_reverb",
    # "/data/ssp/public/dns/dataset/dns1/test_set/synthetic/no_reverb",
]
sr = 16000
offset = 0
limit = false

# -------------------- Validation DNS 4 small set -------------------- #
[validation_dataset_dns_4_non_personalized]
path = "dataset_validation_dns_4_non_personalized.Dataset"
[validation_dataset_dns_4_non_personalized.args]
dataset_dir_list = ["/data/ssp/public/data/dns/dns4_16k/dev_testset/subset"]
sr = 16000
offset = 0
limit = false

# -------------------- Test DNS 1 -------------------- #
[test_dataset_dns_1]
path = "dataset_validation_dns_1.Dataset"
[test_dataset_dns_1.args]
dataset_dir_list = [
    "/data/ssp/public/data/dns/dns1/test_set/synthetic/with_reverb",
    # "/data/ssp/public/dns/dataset/dns1/test_set/synthetic/no_reverb",
]
sr = 16000
offset = 0
limit = false

# -------------------- Test DNS 4  -------------------- #
[test_dataset_dns_4_non_personalized]
path = "dataset_validation_dns_4_non_personalized.Dataset"
[test_dataset_dns_4_non_personalized.args]
dataset_dir_list = ["/data/ssp/public/data/dns/dns4_16k/dev_testset/subset"]
sr = 16000
offset = 0
limit = false

# -------------------- Model -------------------- #
[model]
path = "model.Model"

[model.args]
fdrc = 0.5
n_fft = 320
hop_length = 160
win_length = 320
fb_freqs = 80
num_freqs = 160
sequence_model = "LSTM"
fb_hidden_size = 512
fb_output_activate_function = false
freq_cutoffs = [20, 80]
sb_num_center_freqs = [1, 4, 8]
sb_num_neighbor_freqs = [15, 15, 15]
fb_num_center_freqs = [1, 4, 8]
fb_num_neighbor_freqs = [0, 0, 0]
sb_hidden_size = 384
sb_output_activate_function = false
norm_type = "offline_laplace_norm"
