site_name: AudioZEN
site_description: AudioZEN is a personal project used to conduct the research on the audio/speech signal processing.
repo_name: haoxiangsnr/audiozen
repo_url: https://github.com/haoxiangsnr/audiozen
edit_uri: edit/main/docs/
copyright: Copyright &copy; - 2023 haoxiangsnr

nav:
  - Home: index.md
  - Getting Started:
      - getting_started/prerequisites.md
      - getting_started/project_structure.md
      - getting_started/running_an_experiment.md
      - getting_started/logging_and_visualization.md
      - getting_started/configurations.md
  - Concepts:
      - trainer.md
  - About:
      - FAQ.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - CHANGELOG.md

theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.top
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_root_heading: True
            show_root_full_path: False
            show_category_heading: True
            group_by_category: True
            merge_init_into_class: True

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - toc:
      permalink: true
  - def_list
  - tables
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haoxiangsnr
      name: haoxiangsnr
  generator: false
