site_name: AudioZEN
site_description: AudioZEN is a personal project used to conduct the research on the audio/speech signal processing.
repo_name: haoxiangsnr/audiozen
repo_url: https://github.com/haoxiangsnr/audiozen
edit_uri: edit/main/docs/
copyright: Copyright &copy; - 2023 haoxiangsnr

nav:
  - index.md
  - Getting Started:
      - Installation.md
      - Quickstart:
          - project_structure.md
          - running_an_experiment.md
          - logging_and_visualization.md
      - Concepts:
          - experiment_arguments.md
          - trainer.md
  - API:
      - api/acoustics.md
      - api/loss.md
  - About:
      - FAQ.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - CHANGELOG.md

theme:
  name: material
  font:
    code: Roboto Mono
  palette:
    primary: white
  features:
    - navigation.tabs # tabs in the navigation bar
    - navigation.top # back to top button
    - navigation.expand # expand the navigation
    - navigation.sections
    - content.action.edit # edit button in page
    - content.action.view # view button in page
    - content.code.annotate # code annotation
    - content.code.copy # copy code button
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_root_heading: True
            show_root_full_path: False
            merge_init_into_class: True
            show_bases: false
            show_source: false
            show_docstring_attributes: False
            show_submodules: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: true
  - toc:
      permalink: true
  - def_list
  - tables
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haoxiangsnr
      name: haoxiangsnr
  generator: false

extra_css:
  - stylesheets/extra.css
