[meta]
save_dir = "ultimate_fsb/exp"
description = "This is a description of audiozen experiment."
seed = 20220815
use_amp = false
use_deterministic_algorithms = false

[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256


[loss_function]
path = "torch.nn.MSELoss"
[loss_function.args]

[lr_scheduler]
path = "torch.optim.lr_scheduler.ExponentialLR"
[lr_scheduler.args]
gamma = 0.99


[optimizer]
path = "torch.optim.AdamW"
[optimizer.args]
lr = 0.001

# -------------------- Trainer -------------------- #
[trainer]
path = "trainer.Trainer"
[trainer.args]
max_epoch = 9999
clip_grad_norm_value = 5
save_max_score = true
save_ckpt_interval = 1
patience = 100
validation_interval = 1
max_num_checkpoints = 10

# -------------------- Training data -------------------- #
[train_dataset]
path = "dataloader_noise_h5py.DNS_OTF"
[train_dataset.args]
speech_path = "/mnt/private_xianghao/dnsdatalist/readspeech_hdf5.scp"
noise_path = "/mnt/private_xianghao/dnsdatalist/noise_hdf5.scp"
rir_path = "/mnt/private_xianghao/dnsdatalist/rir_hdf5.scp"
# num_iter_per_epoch = 200000
num_iter_per_epoch = 640000
session_length = 4
input_sr = 16000
target_sr = 16000
snr_range = [-5, 20]
reverb_proportion = 0.75
target_dB_FS = -25
target_dB_FS_floating_value = 10

[train_dataset.dataloader]
batch_size = 32
num_workers = 32
drop_last = true
pin_memory = false

# -------------------- Validate sets -------------------- #
[[validate_dataset]]
path = "dataset_validation_dns_1.Dataset"
[[validate_dataset.args]]
dataset_dir_list = [
    "/apdcephfs/share_1149801/speech_user/tomasyu/xianghao/data/dns1/datasets/test_set/synthetic/with_reverb",
]
sr = 16000
offset = 0
limit = false

[[validate_dataset]]
path = "dataset_validation_dns_1.Dataset"
[[validate_dataset.args]]
dataset_dir_list = [
    "/apdcephfs/share_1149801/speech_user/tomasyu/xianghao/data/dns1/datasets/test_set/synthetic/no_reverb",
]
sr = 16000
offset = 0
limit = false


# -------------------- Test sets -------------------- #
[[test_dataset]]
path = "dataset_validation_dns_1.Dataset"
[test_dataset.args]
dataset_dir_list = [
    "/apdcephfs/share_1149801/speech_user/tomasyu/xianghao/data/dns1/datasets/test_set/synthetic/with_reverb",
]
sr = 16000
offset = 0
limit = false

[[test_dataset]]
path = "dataset_validation_dns_1.Dataset"
[test_dataset.args]
dataset_dir_list = [
    "/apdcephfs/share_1149801/speech_user/tomasyu/xianghao/data/dns1/datasets/test_set/synthetic/no_reverb",
]
sr = 16000
offset = 0
limit = false


# -------------------- Model -------------------- #
[model]
path = "model.Model"
[model.args]
