[meta]
save_dir = "fsb_separator/exp"
description = "This is a description of audiozen experiment."
seed = 3407
use_amp = true
use_deterministic_algorithms = false

[acoustics]
n_fft = 320
win_length = 320
sr = 16000
hop_length = 160


[loss_function]
name = "MultiResSpecLoss"
[loss_function.args]
n_ffts = [240, 480, 960, 1440]
gamma = 0.3
factor = 1
f_complex = 1


[optimizer]
lr = 0.001
beta1 = 0.9
beta2 = 0.999

# -------------------- Trainer -------------------- #
[trainer]
path = "trainer.Trainer"
[trainer.args]
max_epoch = 9999
clip_grad_norm_value = 10
save_max_score = true
save_ckpt_interval = 2

validation_interval = 2
max_num_checkpoints = 50

[train_dataset]
path = "dataset_train.Dataset"
[train_dataset.args]
sr = 16000
clean_dataset = "/data/ssp/public/data/dns/dns4_16k/track2/seg/all_train_own_enrol.txt"
# clean_dataset = "/data/ssp/public/data/dns/dns4_16k/track2/subset/all_train_own_enrol.txt"
point_noise_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/point_noise.txt"
iso_noise_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/noise.txt"
simulated_rir_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/simulated_rir.txt"
real_rir_dataset = "/data/ssp/public/data/dns/dns4_16k/noise_rir/rir.txt"
# MIXTURE
prob_add_itf_spks = 0.95
max_num_itf_spks = 1
sir_range = [-5, 20]
prob_add_point_noise = 0.9
max_num_pt_noises = 1
pt_noise_snr_range = [-5, 20]
prob_add_iso_noise = 0.9
iso_noise_snr_range = [0, 20]
prob_add_rir = 1.0
prob_use_real_rir = 0.5
learning_target = "early"
len_early_rir = 0.1
# ENROLLMENT
enroll_prob_add_point_noises = 0.05
enroll_max_num_pt_noises = 1
enroll_pt_noise_snr_range = [0, 20]
enroll_prob_add_iso_noise = 0.1
enroll_iso_noise_snr_range = [0, 20]
enroll_prob_add_rir = 0.5
enroll_prob_use_real_rir = 0.5
enroll_sample_length = 20
# Others
sample_length = 4
loudness_lvl = -26
loudness_floating_value = 10
return_enroll = true
return_embedding = false

[train_dataset.dataloader]
batch_size = 40
num_workers = 40
drop_last = true
pin_memory = false

# ==================== Validation Track 1 ==================== #
[validation_dataset_dns5_track1]
path = "dataset_validation_dns_5_subset_bothtracks.Dataset"
[validation_dataset_dns5_track1.args]
noisy_dir = "/data/ssp/public/data/dns/dns5_16k/V5_blind_testset/Track1_Headset/noisy_subset"
sr = 16000
offset = 0
limit = false
return_enrollment = true
return_embedding = false

# ==================== Validation Track 2 ==================== #
[validation_dataset_dns5_track2]
path = "dataset_validation_dns_5_subset_bothtracks.Dataset"
[validation_dataset_dns5_track2.args]
noisy_dir = "/data/ssp/public/data/dns/dns5_16k/V5_blind_testset/Track2_Speakerphone/noisy_subset"
sr = 16000
offset = 0
return_enrollment = true
return_embedding = false

# ==================== Test Track 1 ==================== #
[test_dataset_dns5_track1]
path = "dataset_validation_dns_5_subset_bothtracks.Dataset"
[test_dataset_dns5_track1.args]
noisy_dir = "/data/ssp/public/data/dns/dns5_16k/V5_blind_testset/Track1_Headset/noisy"
sr = 16000
offset = 0
limit = false
return_enrollment = true
return_embedding = false

# ==================== Test Track 2 ==================== #
[test_dataset_dns5_track2]
path = "dataset_validation_dns_5_subset_bothtracks.Dataset"
[test_dataset_dns5_track2.args]
noisy_dir = "/data/ssp/public/data/dns/dns5_16k/V5_blind_testset/Track2_Speakerphone/noisy"
sr = 16000
offset = 0
limit = false
return_enrollment = true
return_embedding = false

# -------------------- Model -------------------- #
[model]
path = "model.Model"

[model.args]
fdrc = 0.5
n_fft = 320
hop_length = 160
win_length = 320
fb_freqs = 80
num_freqs = 160
sequence_model = "LSTM"
fb_hidden_size = 768
adapt_fb_hidden_size = 512
adapt_embedding_hidden_size = 512
fb_output_activate_function = false
freq_cutoffs = [20, 80]
sb_num_center_freqs = [1, 4, 8]
sb_num_neighbor_freqs = [15, 15, 15]
fb_num_center_freqs = [1, 4, 8]
fb_num_neighbor_freqs = [0, 0, 0]
adaptor_num_center_freqs = [1, 4, 8]
adaptor_num_neighbor_freqs = [2, 2, 2]
sb_hidden_size = 384
dropout = 0.1
sb_output_activate_function = false
norm_type = "offline_laplace_norm"
