[meta]
save_dir = "sdnn_delays/exp"
seed = 3047
use_amp = false
use_deterministic_algorithms = false
exp_id = "ALIF"
config_path = "/home/quyang/MyProjects/audiozen-main/recipes/intel_ndns/sdnn_delays/ALIF.toml"

[trainer]
path = "sdnn_delays.trainer.Trainer"

[loss_function]
path = "loss.SDNNLoss"

[optimizer]
path = "torch.optim.AdamW"

[lr_scheduler]
path = "torch.optim.lr_scheduler.StepLR"

[model]
path = "sdnn_delays.spk_model.ALIF_Model"

[acoustics]
n_fft = 512
win_length = 512
sr = 16000
hop_length = 128

[train_dataset]
path = "dataloader.DNSAudio"

[validate_dataset]
path = "dataloader.DNSAudio"

[trainer.args]
max_epoch = 9999
clip_grad_norm_value = 10
save_max_score = true
save_ckpt_interval = 1
patience = 10
plot_norm = true
validation_interval = 1
max_num_checkpoints = 10

[loss_function.args]
lam = 0.001
n_fft = 512
hop_length = 128
win_length = 512

[optimizer.args]
lr = 0.001
weight_decay = 0

[lr_scheduler.args]
step_size = 9999
gamma = 0.1

[model.args]
tau_m = 5
neuron_type = "ALIF"

[train_dataset.args]
root = "/datasets/datasets_fullband/training_set/"
limit = false
offset = 0
train = true

[train_dataset.dataloader]
batch_size = 128
num_workers = 10
drop_last = true
pin_memory = false

[validate_dataset.args]
root = "/datasets/datasets_fullband/validation_set/"
limit = false
offset = 0
train = false
