
name: sphinx
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install system build deps
        run: sudo apt-get update -y && sudo apt-get install -y --no-install-recommends build-essential gcc libsndfile1

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install editable
        run: pip install -e .

      - name: Install docs deps
        run: pip install -r docs/requirements.txt

      - name: Sphix Build
        run: sphinx-build -b html docs/source docs/_build

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
